baseURL = "https://leagify.github.io/"
languageCode = "en-us"
title = "Leagify"
theme = "ananke"
SectionPagesMenu = "main"
[params]
favicon = "favicons/favicon.ico"
twitter = "https://twitter.com/leagify"
