baseURL = "https://leagify.github.io/"
languageCode = "en-us"
title = "Leagify"
theme = "ananke"
SectionPagesMenu = "main"
googleAnalytics = "UA-108142998-1"

[params]
favicon = "favicons/favicon.ico"
twitter = "https://twitter.com/leagify"
env = "production"
